### ISSUE TITLE
path search error

### ISSUE THREAD

**Issue by eflister** [epnev/constrained-foopsi#4]
`onPath = ~isempty(strfind(pathCell, ...));` isn't correct (it will always be true), you need `~all(cellfun(@isempty,strfind(pathCell, ...)))`, but i think better to use eg `~isempty(which('cvx_begin'))`

**Comment by epnev** [comment]
changed - thanks.

**Comment by eflister** [comment]
ftr, realized using a `try` block/`catch`ing `'MATLAB:UndefinedFunction'` exception would be more correct
